[workspace]
members = [
    "audio",
    "lib",
    "playback",
    "player",
    "server",
    "tui",
]

[workspace.package]
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music and Podcast Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","youtube","podcast"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "./README.md"
version = "0.7.11"

[workspace.dependencies]
termusic-lib= {path = "lib/" ,version = "0.7.11"}
termusic-playback= {path = "playback/",version = "0.7.11"}
termusic-audio= {path = "audio/",version = "0.7.11"}
ahash = "^0.8"
anyhow = "1.0"
base64 = "0.21"
bytes = "1"
chrono = "^0.4.23"
clap = { version="4", features = ["derive"] }
cpal = "^0.15"
dirs = "5.0"
discord-rich-presence = { version="0.2"}
escaper = "0.1.1"
figment = { version="0.10", features = ["toml"]}
glib = { version="0.17" }
gstreamer = { version="0.20"}
hex = "0.4"
id3 = "1"
image = "0.24"
include_dir = "0.7"
lazy_static = "1.4"
libaes = "0.6"
libmpv-sys = { version = "3" }
lofty = "0.12"
log = "0.4"
lovely_env_logger = "0.6"
md5 = "0.7"
num-bigint = "0.4"
opml = "1"
parking_lot = "^0.12"
pathdiff = { version = "0.2", features = ["camino"] }
percent-encoding = "2.2"
pinyin = "0.9"
pretty_assertions = "1"
quick-xml = "0.28"
rand = "0.8"
regex = "^1.5.5"
rfc822_sanitizer = "0.3" 
rss = "2"
rusqlite = { version = "0.29", features = ["bundled"]}
rust-utils = "^0.7"
sanitize-filename = "0.4"
semver = "^1"
serde = { version = "1.0", features = ["derive"] }
# serde_derive = "*"
serde_json = "1.0"
shellexpand = "3"
souvlaki = "0.6"
symphonia = { version = "0.5.1",  features = ["default","aac","mp3","isomp4","alac","flac"]}
sysinfo = "^0.29"
textwrap = "0.16"
toml = "0.7"
tuirealm = { version = "1", features = ["serialize"] }
tui-realm-stdlib = "1"
tui-realm-treeview = "1"
unicode-segmentation = "1.10"
unicode-width = "^0.1.8"
ureq = "2"
urlencoding = "2"
# viuer = { version = "0.6", features = ["sixel"] }
viuer = "0.6"
walkdir = "2"
wildmatch = "2"
yaml-rust = "^0.4.5"
ytd-rs = { version = "0.1", features = ["yt-dlp"]}
reqwest = { version="0.11", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
tonic = "0.9"
prost = "0.11"
tonic-build = "0.9"
async-trait = "0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.release]
# lto = true
# panic = 'abort'
# opt-level = 'z'
# codegen-units = 1
